import type { Metadata } from 'next';
import Navbar from '../../components/Navbar';

export const metadata: Metadata = {
  title: 'Terms of Use — dotcomgen',
  description: 'Terms of Use and Service Agreement for dotcomgen domain name generator.',
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="container" style={{ flex: 1 }}>
        <header>
          <h1>TERMS OF USE</h1>
          <p className="subtitle">Service Agreement & Usage Terms</p>
          <div className="last-updated-badge">Last Updated: July 31, 2026</div>
        </header>

        <article className="glass-panel legal-card">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using <strong>dotcomgen</strong> ("the Service"), you agree to be bound by these Terms of Use. If you do not agree to all terms and conditions, you may not access or use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            dotcomgen provides an AI-powered domain name generation and real-time DNS availability checking service. The Service assists founders, creators, and businesses in brainstorming brandable <code>.com</code> domain names based on user prompts and parameters.
          </p>

          <h2>3. Domain Availability Disclaimer & Registration</h2>
          <p>
            Domain name availability checks presented on dotcomgen are queried in real time via DNS and WHOIS registry records. Please note:
          </p>
          <ul>
            <li>
              <strong>No Guarantee:</strong> Availability data is provided for informational purposes only. Domain names can be registered by third parties at any moment prior to your checkout with an accredited registrar.
            </li>
            <li>
              <strong>No Direct Registration:</strong> dotcomgen does not act as a domain registrar and does not sell or hold domain registrations directly.
            </li>
          </ul>

          <h2>4. User Accounts, Credits & Stripe Billing</h2>
          <p>
            To access certain features (such as saving domains or generating additional suggestions beyond free limits), you may create an account via Supabase Auth (email or Google OAuth).
          </p>
          <ul>
            <li>
              <strong>Paid Tiers:</strong> Subscriptions (e.g. Starter, Pro, Unlimited) and credit top-ups are processed securely via <strong>Stripe</strong>.
            </li>
            <li>
              <strong>Billing & Subscriptions:</strong> Billed charges are non-refundable except where required by law or specified during checkout. You may manage or cancel your active subscription at any time.
            </li>
            <li>
              <strong>Account Responsibility:</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activities occurring under your account.
            </li>
          </ul>

          <h2>5. Affiliate & External Registrar Links</h2>
          <p>
            The Service contains links redirecting users to third-party accredited domain registrars (including but not limited to Namecheap, GoDaddy, Hover, and Porkbun).
          </p>
          <p>
            Some links may include affiliate tracking identifiers (such as Impact Radius verification). If you purchase a domain or service through these links, dotcomgen may receive an affiliate commission at no additional cost to you. dotcomgen is not responsible for transactions, pricing, or customer support provided on external registrar websites.
          </p>

          <h2>6. Intellectual Property & Trademark Responsibility</h2>
          <p>
            Suggestions generated by dotcomgen are produced via artificial intelligence models. dotcomgen makes no warranty or representation that suggested domain names are free from third-party trademark rights or intellectual property infringements.
          </p>
          <p>
            <strong>User Duty:</strong> You are solely responsible for performing thorough trademark and legal searches before purchasing, branding, or registering any domain name suggested by the Service.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            The Service is provided on an <strong>"AS IS"</strong> and <strong>"AS AVAILABLE"</strong> basis without warranties of any kind, whether express or implied. To the maximum extent permitted by applicable law, dotcomgen shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of or inability to use the Service.
          </p>

          <h2>8. Changes to Terms</h2>
          <p>
            dotcomgen reserves the right to modify or update these Terms of Use at any time. Continued use of the Service after changes are posted constitutes your acceptance of the updated terms.
          </p>
        </article>
      </main>
    </>
  );
}
